server:
  port: 8015
  tomcat:
    uri-encoding: UTF-8
spring:
  main:
    allow-bean-definition-overriding: true
  thymeleaf:
    prefix: classpath:/static/
    mode: LEGACYHTML5
  web:
    resources:
      static-locations:  classpath:/static/
  datasource:
    #    url: jdbc:mysql://192.168.0.68:3306/search?useSSL=false&useUnicode=true&character_set_server=utf8mb4
    url: jdbc:mysql://119.8.102.49:3306/movie?useSSL=false&useUnicode=true&character_set_server=utf8mb4
    username: movies
    password: ZkH5nKwLhZMeWkLt
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 119.8.56.223
    #    host: 127.0.0.1
    port: 8080
    password: 2pmnpw47@